/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer'
import styles from './index.module.scss'

export default function Home() {
  return (
    <div className={styles.index}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container_1}>
        <div className={styles.head}>
          <h2>Design Portfolio</h2>
          <div></div>
        </div>
        <div className={styles.nav}>
          <Link href={'/#about'}>
            <p>about</p>
          </Link>
          <Link href={'/works'}>
            <p>Works</p>
          </Link>
          <Link href={''}>
            <p>Contact</p>
          </Link>
        </div>
        <h1>Hi, I'm <span>Heritage Egwim</span>,</h1>
        <h2>and I'm a UI/UX Designer.</h2>
        <div className={styles.case_studies}>
          <img src='https://fritani.my.canva.site/uiux-portfolio/videos/435164c1555a336ba7a82f786005d2d6.gif' alt='hd'/>
          <Link href={'/case-studies'}>
            <p>View CASESTUDIES</p>
          </Link>
        </div>
      </div>
      
      <div id='about' className={styles.container_2}>
        <div className={styles.about}>
          <h2>About Me</h2>
          <p>Hi! I'm Heritage.</p>
          <p>I am passionate about anything design. I make user-friendly designs that can be implemented and are sustainable.</p>
          <p>Over the period of my learning and constant work practice, 
            I developed an interest in how people respond positively to interactive interfaces that give digital solutions to their challenges. Having this knowledge, 
            I create designs that solve real world challenges.
          </p>
          <p>I am open to learning more in this design field in order to deliver better products.</p>
        </div>
        <div className={styles.image}>
          <svg  viewBox="0 0 504.3 526.7" preserveAspectRatio="none" style={{transform: 'scale(1, 1)', overflow: 'visible', top: '0%', left: '0%', display: 'block', width: '100%', position: 'absolute', opacity: 1, height: '100%'}}>
            <g>
            <clipPath >
            <path d="M319.6000122070312,50.8 C404.8000091552734,41.19999961853027 435.50001373291013,107.50000076293945 435.50001373291013,107.50000076293945 C435.50001373291013,107.50000076293945 498.1000122070312,122.40000038146972 501.2000106811523,189.90000228881837 C504.3000091552734,257.400004196167 469.6000102996826,279.3000038146973 469.6000102996826,279.3000038146973 C469.6000102996826,279.3000038146973 489.80001106262205,321.50000457763673 471.3000103473663,378.2000053405762 C452.8000096321106,434.90000610351564 413.2000118732452,441.8000038146973 413.2000118732452,441.8000038146973 C413.2000118732452,441.8000038146973 403.90001168251035,482.40000228881837 331.7000118732452,504.6000030517578 C259.50001492500303,526.7000034332275 235.20001187324524,487.1000030517578 235.20001187324524,487.1000030517578 C235.20001187324524,487.1000030517578 172.80001034736634,496.5000026702881 114.20001187324524,480.80000286102296 C55.600013399124144,465.1000030517578 50.600013399124144,386.6000059127808 50.600013399124144,386.6000059127808 C50.600013399124144,386.6000059127808 2.799999976158142,348.50001220703126 1.500000001490116,279.09998779296876 C1.4901160305669237E-9,199.69998626708986 32.79999923855066,166.09998779296876 32.79999923855066,166.09998779296876 C32.79999923855066,166.09998779296876 11.89999962002039,107.09998779296875 54.59999847561121,65.09998779296875 C116.39999771267176,4.299988555908203 157.2999954238534,32.09998779296875 157.2999954238534,32.09998779296875 C157.2999954238534,32.09998779296875 193.8999938979745,-1.0681152343927636E-5 239.09999847561122,4.699988174438476 C284.3000030532479,9.399987030029298 319.6000122070312,50.8 319.6000122070312,50.8">
            </path>
            </clipPath>
            <g >
            <g  style={{transform:'scale(1, 1)',transformOrigin:'252.5px 263px'}}>
            <image  href="https://fritani.my.canva.site/uiux-portfolio/images/97d80c95e0eb91d2e54637c6480795de.jpg" width="499.94591699px" height="666.59455598px" preserveAspectRatio="none" style={{transform:'translate(1.45007674px, -81.94657387px) rotate(0deg)',transformOrigin:'249.97295849px 333.29727799px',opacity:1.0}}>
            </image>
            </g>
            </g>
            </g>
          </svg>
        </div>
      </div>

      <div className={styles.container_3}>
        <div className={styles.head}>
          <h2>Credentials</h2>
          <div></div>
        </div>
        <div className={styles.box}>
          <h4>Education</h4>
          <div>
            <p>ZEROTOMASTERY ACADEMY</p>
            <p>UIUX certification in progress</p>
            <p>(August 2021-Current date)</p>
          </div>
        </div>

        <div className={styles.box}>
          <h4>Skills</h4>
          <div>
            <p>User-Centered Design</p>
            <p>Wireframing</p>
            <p>Prototyping</p>
            <p>Creative writing</p>
          </div>
        </div>

       
      </div>
      
      
      <Footer/>
    </div>
  )
}
